---
title: "Wairakei JAGS Simulation"
author: "Logan Wu"
date: "5/24/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('rjags')
library('tidyverse')
```

```{r}
data.df <- read.csv('../../wairakei_data/data.csv') %>%
  # filter(well %in% c('wk255', 'wk256')) %>%
  mutate(date = as.Date(date, format="%y/%m/%d"),
         well_id = as.numeric(droplevels(well)))
head(data.df)

whp_pred <- c(15)
well_id_pred <- unique(data.df$well_id)
# date_pred <- seq(0, floor(max(data.df$date_numeric)/365))*365
date_pred <- as.numeric(difftime(Sys.time(), min(data.df$date)))
data.pred <- expand.grid(whp=whp_pred, well_id=well_id_pred, date_numeric=date_pred)
data.in <- bind_rows(data.df, data.pred)

data <- as.list(data.in)
# data$m <- length(unique(wells.distinct))

data$n <- nrow(data.in)
```

```{r}
Model = "model {
  # fit linear regression to well
  for (i in 1:n) {
    mu[i] <- beta_well * well_id[i] *(Intercept + beta_whp * whp[i] ) + beta_date * date_numeric[i]
    mf[i] ~ dnorm(mu[i], tau)
  }

  Intercept ~ dnorm(0, 1e-4)
  beta_whp ~ dnorm(0, 1e-4)
  beta_date ~ dnorm(0, 1e-4)
  beta_well ~ dnorm(0, 1e-4)
  tau ~ dgamma(1e-2, 1e-2)

  # make predictions
  wk255_pred <- mu[n-1]
  wk256_pred <- mu[n]
}"
parameters = c('Intercept', 'beta_whp', 'beta_date', 'wk255_pred', 'wk256_pred')
burn_in = 1000
steps = 5000
foo <- jags.model(textConnection(Model), data=data, n.chains=2, quiet=TRUE) 
update(foo, burn_in, progress.bar='none')
out <- coda.samples(model=foo, variable.names=parameters, n.iter=steps, progress.bar='none')
outframe <-as.data.frame(as.matrix(out))
```

```{r, echo=FALSE}
df.plot <- outframe %>%
  gather(parameter, value)

plots <- list()
plot <- ggplot(df.plot, aes(x=value)) +
    geom_density()
for (p in unique(df.plot$parameter)) {
  df.param <- df.plot %>% filter(parameter==p)
  print(plot %+% ggtitle(paste("Posterior density for", p)) %+% df.param)
}
```

```{r}
df.pred.post <- outframe %>%
  select(wk255_pred, wk256_pred) %>%
  gather(well, value)
ggplot(data.df, aes(x=whp, y=mf, color=date_numeric, shape=well)) +
  geom_point() +
  geom_violin(data=df.pred.post,
              aes(x=whp_pred, y=value, linetype=well),
              col='blue',
              alpha=0)
```

```{r}
Model = "model {
  # fit individual regressions to wells
  for (i in 1:n) {
    mu[i] <- Intercept[well_id[i]] + beta_whp[well_id[i]] * whp[i] + beta_date[well_id[i]] * date_numeric[i]
    mf[i] ~ dnorm(mu[i], tau)
  }

  for (j in 1:m) {
    Intercept[j] ~ dnorm(0, 1e-4)
    beta_whp[j] ~ dnorm(0, 1e-4)
    beta_date[j] ~ dnorm(0, 1e-4)
  }

  tau ~ dgamma(1e-2, 1e-2)

  # make predictions
  wk255_pred <- mu[n-1]
  wk256_pred <- mu[n]
}"
parameters = c('wk255_pred', 'wk256_pred')
burn_in = 1000
steps = 5000
foo <- jags.model(textConnection(Model), data=data, n.chains=2, quiet=TRUE) 
update(foo, burn_in, progress.bar='none')
out <- coda.samples(model=foo, variable.names=parameters, n.iter=steps, progress.bar='none')
outframe <-as.data.frame(as.matrix(out))
```
```{r}
model = "
model {
a <- sum(x[y[1,]])
b <- sum(x[y[2,1:2]])
}
"
data = list(x=c(10,20,40), y=matrix(c(1,2,1,3), nrow=2))
foo = jags.model(textConnection(model), data=data)
jags.samples(model=foo, n.iter=100, variable.names=c('a', 'b'))
```